### PR TITLE
 Return 400 for malformed GraphQL JSON requests

### LINKED ISSUE #555: Sending malformed Query request results in HTTP 500 instead of HTTP 400
### Expected Behavior

Server should respond with HTTP 400 to malformed requests.
image
Instead of RuntimeException if we can throw JsonParseException then it will be easy to handle that error in GlobalErrorHandler because RuntimeException is very generic and if we handle RuntimeException then it will handle other exceptions also.

### Actual Behaviour

Unexpected error occurred: Error deserializing object from JSON: Unexpected character ('q' (code 113)): was expecting double-quote to start field name
 at [Source: (byte[]) with 500 error.
 
 

### Steps To Reproduce

To Reproduce:

1. Setup a server with any GraphQL schema.
2. Send POST request to the server with request body set to "Bad request" or any other invalid Json.
3. See HTTP 500 error instead of HTTP 400.

### Environment Information

OS: Windows
Request sent from Postman
micronaut-graphql version=4.1.4

### Example Application

_No response_

### Version

4.1.4

### PR DESCRIPTION
**Pull request by lissam1**
-  Map malformed GraphQL request body and variables JSON parsing failures to HTTP 400 and add regression tests for both paths. 
-Closes: #555

### CODE REVIEW

File: graphql/src/main/java/io/micronaut/configuration/graphql/GraphQLController.java [hunk 1]
```diff
@@ -147,7 +148,12 @@ public Publisher<MutableHttpResponse<String>> post(
         // }
 
         if (APPLICATION_JSON_TYPE.equals(contentType)) {
-            GraphQLRequestBody request = graphQLJsonSerializer.deserialize(body, GraphQLRequestBody.class);
+            GraphQLRequestBody request;
+            try {
+                request = graphQLJsonSerializer.deserialize(body, GraphQLRequestBody.class);
+            } catch (RuntimeException e) {
```
Comment (sdelamo) [inline graphql/src/main/java/io/micronaut/configuration/graphql/GraphQLController.java:154]: Can we catch something more specific than `RuntimeException`?
